return {
  -- {
  --   "benlubas/molten-nvim",
  --   version = "^1.0.0", -- use version <2.0.0 to avoid breaking changes
  --   dependencies = { "3rd/image.nvim" },
  --   build = ":UpdateRemotePlugins",
  --   init = function()
  --     -- these are examples, not defaults. Please see the readme
  --     vim.g.molten_image_provider = "image.nvim"
  --     vim.g.molten_output_win_max_height = 20
  --   end,
  --   -- mappings = {
  --   --   { "<leader>re", "<cmd>MoltenEvaluateOperator<CR>", desc = "Evaluate operator", silent = true },
  --   --   { "<leader>ros", "<cmd>noautocmd MoltenEnterOutput<CR>", desc = "Open output window", silent = true },
  --   --   { "<leader>rR", "<cmd>MoltenReevaluateCell<CR>", desc = "Re-eval cell", silent = true },
  --   --   { "v <leader>r", "<cmd><C-u>MoltenEvaluateVisual<CR>gv", desc = "Execute visual selection", silent = true },
  --   --   { "<leader>roh", "<cmd>MoltenHideOutput<CR>", desc = "Close output window", silent = true },
  --   --   { "<leader>rd", "<cmd>MoltenDelete<CR>", desc = "Delete Molten cell", silent = true },
  --   --   { "<leader>rx", "<cmd>MoltenOpenInBrowser<CR>", desc = "Open output in browser", silent = true },
  --   -- },
  -- },
  -- {
  --   "3rd/image.nvim",
  --   opts = {
  --     backend = "kitty", -- whatever backend you would like to use
  --     max_width = 100,
  --     max_height = 12,
  --     max_height_window_percentage = math.huge,
  --     max_width_window_percentage = math.huge,
  --     window_overlap_clear_enabled = true, -- toggles images when windows are overlapped
  --     window_overlap_clear_ft_ignore = { "cmp_menu", "cmp_docs", "" },
  --     editor_only_render_when_focused = true, -- auto show/hide images when the editor gains/looses focus
  --     tmux_show_only_in_active_window = false, -- auto show/hide images in the correct Tmux window (needs visual-activity off)
  --     hijack_file_patterns = { "*.png", "*.jpg", "*.jpeg", "*.gif", "*.webp" },
  --   },
  -- },
}
