return {
  -- "ahmedkhalf/project.nvim",
  -- opts = {
  --   -- manual_mode = false,
  --     -- Show hidden files in telescope
  --   -- show_hidden = true,
  --
  --   -- When set to false, you will get a message when project.nvim changes your
  --   -- directory.
  --   silent_chdir = false,
  --   -- detection_methods = {"pattern"},
  --   -- patterns = { "!.git", "_darcs", ".hg", ".bzr", ".svn", "Makefile", "package.json" },
  --
  --
  -- },
  -- event = "VeryLazy",
  -- config = function(_, opts)
  --   require("project_nvim").setup(opts)
  --   local history = require("project_nvim.utils.history")
  --   history.delete_project = function(project)
  --     for k, v in pairs(history.recent_projects) do
  --       if v == project.value then
  --         history.recent_projects[k] = nil
  --         return
  --       end
  --     end
  --   end
  --   LazyVim.on_load("telescope.nvim", function()
  --     require("telescope").load_extension("projects")
  --   end)
  -- end,
}
